# https://circleci.com/docs/2.0/language-android/#sample-configuration
# https://github.com/shadowsocks/shadowsocks-android/blob/master/.circleci/config.yml

version: 2
jobs:
  build:
    environment:
      WD: code
    working_directory: ~/code
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      # https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/android/images
      # https://en.wikipedia.org/wiki/Debian_version_history
      # - image: circleci/android:api-28-ndk
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Stop for SSH
          command: |
            false
      # - run:
      #     name: Align & sign APK
      #     command: |
      #       true
      # - store_artifacts:
      #     path: mobile/build/outputs/apk/release/
      #     destination: mobile
      # - store_artifacts:
      #     path: tv/build/outputs/apk/release/
      #     destination: tv

      # - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      #     path: app/build/test-results
      # # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples